import Head from "next/head";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import { allPosts, Post } from "contentlayer/generated";
import { GetStaticPropsContext } from "next";

export async function getStaticPaths() {
  const paths = allPosts.map((post) => post.url);
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }: GetStaticPropsContext) {
  const slug = params?.slug?.toString().toLowerCase();
  if (!slug) {
    return {
      notFound: true,
    };
  }
  const post = allPosts.find(({ _id }) => _id.slice(0, -3) === slug);
  return { props: { post } };
}

const PostLayout = ({ post }: any) => {
  return (
    <>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" ">
        <article className="mx-6 sm:mx-auto max-w-2xl py-16">
          <div className="mb-6">
            <h1 className="mb-1 text-3xl font-bold text-white text-center">
              {post.title}
            </h1>
            <time
              dateTime={post.date}
              className="text-sm text-slate-600 flex justify-center mb-20"
            >
              {format(parseISO(post.date), "LLLL d, yyyy")}
            </time>

            <div
              className="text-neutral-200 prose prose-md prose-neutral prose-invert"
              dangerouslySetInnerHTML={{ __html: post.body.html }}
            />
          </div>
        </article>
        <div className="flex justify-center">
          <Link
            href="/"
            className="border-2 border-neutral-800 rounded-xl hover:rounded-md py-1 px-3 text-md  text-gray-200 bg-neutral-800 hover:border-neutral-700 hover:bg-neutral-800/70 transition duration-500 ease-in-out cursor-pointer mb-28"
          >
            Back
          </Link>
        </div>
      </div>
    </>
  );
};
export default PostLayout;
